# Generated by Django 4.0.4 on 2022-05-31 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('year_of_release', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('num_of_ep', models.CharField(max_length=125)),
                ('producer', models.CharField(max_length=125)),
                ('desc', models.TextField()),
                ('teg', models.CharField(max_length=225)),
                ('category', models.ManyToManyField(related_name='category_product', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='product/video/%Y/%m/%d/')),
                ('desc', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_video', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bookmark', models.BooleanField(blank=True, default=False, null=True)),
                ('rate', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rela_product', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rela_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/image/%Y/%m/%d/')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(related_name='user_product', through='products.ProductUserRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
