# Generated by Django 4.0.4 on 2022-05-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortepisoddesc',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_epis_desc', to='products.product'),
        ),
        migrations.AddField(
            model_name='videoproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_video', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product/image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='videoproduct',
            name='video',
            field=models.FileField(upload_to='product/video/%Y/%m/%d/'),
        ),
    ]
