# Generated by Django 4.0.4 on 2022-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_shortepisoddesc_product_videoproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category_product', through='products.ProductCategoryRelation', to='categories.category'),
        ),
    ]
