# Generated by Django 4.0.4 on 2022-05-28 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_remove_product_rating_productuserrelation_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuserrelation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productuserrelation',
            name='user',
        ),
        migrations.AddField(
            model_name='productuserrelation',
            name='product_prod_rel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rela_product', to='products.product'),
        ),
        migrations.AddField(
            model_name='productuserrelation',
            name='user_prod_rel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rela_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
