# Generated by Django 4.0.4 on 2022-05-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('type_message', models.PositiveSmallIntegerField(choices=[(1, 'Правообладание и юридические аспекты'), (2, 'Вопросы рекламы'), (3, 'Проблемы на сайте'), (4, 'Пожелания и хотелки')])),
                ('text', models.TextField()),
            ],
        ),
    ]
