# Generated by Django 4.0.4 on 2022-06-01 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='updated_at',
        ),
    ]
