# Generated by Django 4.0.4 on 2022-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecomment',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
