# Generated by Django 4.0.4 on 2022-05-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
